[versions]
kotlin = "2.3.0"
testballoon = "0.8.2-K2.3.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-powerassert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
testballoon = { id = "de.infix.testBalloon", version.ref = "testballoon" }

[libraries]
testballoon-framework-core = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "testballoon" }
